# Generated by Django 4.2.1 on 2023-05-25 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogCocina', '0002_remove_articulo_fecha_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
