# Generated by Django 4.2.1 on 2023-05-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogCocina', '0003_articulo_creador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='desarrollo',
            new_name='cuerpo',
        ),
    ]
