# Generated by Django 4.2.1 on 2023-05-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogCocina', '0004_rename_desarrollo_articulo_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
