# Generated by Django 4.2.1 on 2023-05-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogCocina', '0005_articulo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
    ]
